/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

/**
 *
 * @author Heiner Perez
 */
public class administrador2 extends javax.swing.JFrame {

    /**
     * Creates new form administrador2
     */
    public administrador2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtoncolsulta = new javax.swing.JButton();
        jButtonregis = new javax.swing.JButton();
        jButtonactu = new javax.swing.JButton();
        jButtonreporte = new javax.swing.JButton();
        jButtoninturno = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COLVISE S.A.S");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 270, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vigilante.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jButtoncolsulta.setBackground(new java.awt.Color(51, 51, 255));
        jButtoncolsulta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtoncolsulta.setForeground(new java.awt.Color(255, 255, 255));
        jButtoncolsulta.setText("Consulta de Empleado");
        jButtoncolsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncolsultaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoncolsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 200, -1));

        jButtonregis.setBackground(new java.awt.Color(51, 51, 255));
        jButtonregis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonregis.setForeground(new java.awt.Color(255, 255, 255));
        jButtonregis.setText("Registrar Empleado");
        jButtonregis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonregis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 200, -1));

        jButtonactu.setBackground(new java.awt.Color(51, 51, 255));
        jButtonactu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonactu.setForeground(new java.awt.Color(255, 255, 255));
        jButtonactu.setText("Actualizar Empleado");
        jButtonactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonactuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonactu, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 250, 200, -1));

        jButtonreporte.setBackground(new java.awt.Color(51, 51, 255));
        jButtonreporte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonreporte.setForeground(new java.awt.Color(255, 255, 255));
        jButtonreporte.setText("Ver Reportes");
        jButtonreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonreporteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonreporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 380, 200, -1));

        jButtoninturno.setBackground(new java.awt.Color(51, 51, 255));
        jButtoninturno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtoninturno.setForeground(new java.awt.Color(255, 255, 255));
        jButtoninturno.setText("Registro de Turnos");
        jButtoninturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoninturnoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoninturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 310, 200, -1));

        jButtonSalir.setBackground(new java.awt.Color(51, 51, 255));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGRESAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 509, 536));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Administrador administrador = new Administrador();
        administrador.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonreporteActionPerformed
       Reportes reportes = new Reportes();
        reportes.show();
        this.dispose();
    }//GEN-LAST:event_jButtonreporteActionPerformed

    private void jButtonregisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregisActionPerformed
        Registro registro = new Registro();
        registro.show();
        this.dispose();
    }//GEN-LAST:event_jButtonregisActionPerformed

    private void jButtoncolsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncolsultaActionPerformed
        Consulta consulta = new Consulta();
        consulta.show();
        this.dispose();
    }//GEN-LAST:event_jButtoncolsultaActionPerformed

    private void jButtonactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonactuActionPerformed
       Actualizar actualizar = new Actualizar();
        actualizar.show();
        this.dispose();
    }//GEN-LAST:event_jButtonactuActionPerformed

    private void jButtoninturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoninturnoActionPerformed
       ingresoturnos Ingresoturnos = new ingresoturnos();
        Ingresoturnos.show();
        this.dispose();
    }//GEN-LAST:event_jButtoninturnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrador2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrador2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonactu;
    private javax.swing.JButton jButtoncolsulta;
    private javax.swing.JButton jButtoninturno;
    private javax.swing.JButton jButtonregis;
    private javax.swing.JButton jButtonreporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
