
 
package Inicio;

import Herencia.secretaria;
import com.sun.istack.internal.logging.Logger;
import conectar.conectar;
import java.util.logging.Level;
import javax.swing.JOptionPane;



public final class Registro extends javax.swing.JFrame {

   
    
    
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        limpiar();
        bloquear();
    }
    void limpiar(){
    t_identificacion.setText("");
    t_nombre.setText("");
    t_apellidos.setText("");
    t_direccion.setText("");
    t_correo.setText("");
    t_telefono.setText("");
    t_usuario.setText("");
    t_contraseña.setText("");
      
    }
    void bloquear(){
    t_identificacion.setEnabled(false);
    t_nombre.setEnabled(false);
    t_apellidos.setEnabled(false);
    t_direccion.setEnabled(false);
    t_correo.setEnabled(false);
    t_telefono.setEnabled(false);
    t_usuario.setEnabled(false);
    t_contraseña.setEnabled(false);
    b_nuevo.setEnabled(true);
    b_registrar.setEnabled(false);
    b_cancelar.setEnabled(false);
    }
    
    void desbloquear(){
     t_identificacion.setEnabled(true);
    t_nombre.setEnabled(true);
    t_apellidos.setEnabled(true);
    t_direccion.setEnabled(true);
    t_correo.setEnabled(true);
    t_telefono.setEnabled(true);
    t_usuario.setEnabled(true);
    t_contraseña.setEnabled(true);
    b_nuevo.setEnabled(false);
    b_registrar.setEnabled(true);
    b_cancelar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t_identificacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxcargo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        t_telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t_apellidos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t_contraseña = new javax.swing.JTextField();
        t_direccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t_correo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        t_usuario = new javax.swing.JTextField();
        b_nuevo = new javax.swing.JButton();
        d_nacimiento = new com.toedter.calendar.JDateChooser();
        b_registrar = new javax.swing.JButton();
        b_cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 255));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("SALIR");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGRESAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Identificacion ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        t_identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_identificacionActionPerformed(evt);
            }
        });
        getContentPane().add(t_identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 140, -1));

        jLabel4.setBackground(new java.awt.Color(51, 51, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cargo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, -1));

        jComboBoxcargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretaria", "Vigilante", "Supervisor" }));
        jComboBoxcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxcargoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 51, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellidos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        t_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(t_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 120, -1));

        jLabel6.setBackground(new java.awt.Color(0, 51, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Dirección");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 20));

        t_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(t_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 150, -1));

        jLabel7.setBackground(new java.awt.Color(0, 51, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombres");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 51, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telefono");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        t_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_apellidosActionPerformed(evt);
            }
        });
        getContentPane().add(t_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 150, -1));

        jLabel9.setBackground(new java.awt.Color(0, 51, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 51, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contraseña");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        t_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_contraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(t_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 160, -1));

        t_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_direccionActionPerformed(evt);
            }
        });
        getContentPane().add(t_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 150, -1));

        jLabel11.setBackground(new java.awt.Color(0, 51, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Correo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        t_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_correoActionPerformed(evt);
            }
        });
        getContentPane().add(t_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, -1));

        jLabel12.setBackground(new java.awt.Color(0, 51, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Usuario");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        t_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(t_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 160, -1));

        b_nuevo.setBackground(new java.awt.Color(51, 51, 255));
        b_nuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        b_nuevo.setText("NUEVO");
        b_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(b_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));
        getContentPane().add(d_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 120, -1));

        b_registrar.setBackground(new java.awt.Color(51, 51, 255));
        b_registrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_registrar.setForeground(new java.awt.Color(255, 255, 255));
        b_registrar.setText("REGISTRAR");
        b_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(b_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        b_cancelar.setBackground(new java.awt.Color(51, 51, 255));
        b_cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        b_cancelar.setText("CANCELAR");
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(b_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        administrador2 Administrador2 = new administrador2();
        Administrador2.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nuevoActionPerformed
        // TODO add your handling code here:
        desbloquear();
        t_identificacion.requestFocus();
    }//GEN-LAST:event_b_nuevoActionPerformed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
    bloquear();
    limpiar();
    }//GEN-LAST:event_b_cancelarActionPerformed

    private void b_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_registrarActionPerformed
      String opcion = jComboBoxcargo.getSelectedItem().toString();
      if (opcion.equalsIgnoreCase("secretaria")){
          secretaria secre = new secretaria();
        secre.ide = t_identificacion.getText();
        secre.nom = t_nombre.getText();
        secre.apell = t_apellidos.getText();
        secre.dir = t_direccion.getText();
        secre.tel = t_telefono.getText();
        secre.usua = t_usuario.getText();
        secre.contra = t_contraseña.getText();
        secre.f_nac= d_nacimiento.getDateFormatString();
        secre.cor=t_correo.getText();
        
          System.out.println(secre.toString());
          PreparedStatement pps =  conect.prepareStatement("INSERT INTO secretaria(identificacion, nombres, apellidos, direccion,telefono,fecha_nacimiento,correo,usuario,clave)VALUE(?,?,?,?,?,?,?,?,?)");
          pps.setString(1,t_identificacion.getText());
          pps.setString(2,t_nombre.getText());
          pps.setString(3,t_apellidos.getText());
          pps.setString(4,t_direccion.getText());
          pps.setString(5,t_telefono.getText());
          pps.setString(6,d_nacimiento.getDateFormatString());
          pps.setString(7,t_correo.getText());
          pps.setString(8,t_usuario.getText());
          pps.setString(9,t_contraseña.getText());
          JOptionPane.showMessageDialog(null, "Registro Exitoso");
        
    }           
    }//GEN-LAST:event_b_registrarActionPerformed

    private void t_identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_identificacionActionPerformed
       t_identificacion.transferFocus();
    }//GEN-LAST:event_t_identificacionActionPerformed

    private void t_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nombreActionPerformed
         t_nombre.transferFocus();
    }//GEN-LAST:event_t_nombreActionPerformed

    private void t_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_apellidosActionPerformed
         t_apellidos.transferFocus();
    }//GEN-LAST:event_t_apellidosActionPerformed

    private void t_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_direccionActionPerformed
        t_direccion.transferFocus();
    }//GEN-LAST:event_t_direccionActionPerformed

    private void t_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_correoActionPerformed
         t_correo.transferFocus();
    }//GEN-LAST:event_t_correoActionPerformed

    private void t_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_telefonoActionPerformed
         t_telefono.transferFocus();
    }//GEN-LAST:event_t_telefonoActionPerformed

    private void t_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usuarioActionPerformed
         t_usuario.transferFocus();
    }//GEN-LAST:event_t_usuarioActionPerformed

    private void t_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_contraseñaActionPerformed
         t_contraseña.transferFocus();
    }//GEN-LAST:event_t_contraseñaActionPerformed

    private void jComboBoxcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxcargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxcargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Registro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancelar;
    private javax.swing.JButton b_nuevo;
    private javax.swing.JButton b_registrar;
    private com.toedter.calendar.JDateChooser d_nacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxcargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t_apellidos;
    private javax.swing.JTextField t_contraseña;
    private javax.swing.JTextField t_correo;
    private javax.swing.JTextField t_direccion;
    private javax.swing.JTextField t_identificacion;
    private javax.swing.JTextField t_nombre;
    private javax.swing.JTextField t_telefono;
    private javax.swing.JTextField t_usuario;
    // End of variables declaration//GEN-END:variables

    private conectar conectar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
